export const englishP4Questions = [
  {
    id: "eng-p4-sva-l3-1",
    subject: "English",
    grade: "P4",
    topic: "Subject-Verb Agreement",
    level: 3,
    difficulty: "Easy",
    track: "Core",
    type: "multiple",
    prompt: "Choose the correct verb: The dog ___ in the garden.",
    helpText: "One dog needs a singular verb.",
    options: ["run", "runs", "running", "are run"],
    answer: "runs",
    explanation: "'Dog' is singular, so we use 'runs'.",
    hint: "Think: he runs, she runs, it runs."
  },
  {
    id: "eng-p4-sva-l4-1",
    subject: "English",
    grade: "P4",
    topic: "Subject-Verb Agreement",
    level: 4,
    difficulty: "Medium",
    track: "Core",
    type: "multiple",
    prompt: "The children ___ happily in the playground.",
    helpText: "More than one child — plural subject.",
    options: ["plays", "is playing", "play", "playsed"],
    answer: "play",
    explanation: "'Children' is plural, so the verb is 'play'.",
    hint: "They play, we play, children play."
  },
  {
    id: "eng-p4-prep-l3-1",
    subject: "English",
    grade: "P4",
    topic: "Prepositions & Conjunctions",
    level: 3,
    difficulty: "Easy",
    track: "Core",
    type: "multiple",
    prompt: "The cat hid ___ the table.",
    helpText: "Where is the cat?",
    options: ["on", "under", "between", "through"],
    answer: "under",
    explanation: "Cats often hide under furniture.",
    hint: "Picture the cat below the table."
  },
  {
    id: "eng-p4-prep-l5-1",
    subject: "English",
    grade: "P4",
    topic: "Prepositions & Conjunctions",
    level: 5,
    difficulty: "Medium",
    track: "Core",
    type: "multiple",
    prompt: "I wanted to go out, ___ it was raining.",
    helpText: "The second part contrasts with the first.",
    options: ["and", "but", "because", "so"],
    answer: "but",
    explanation: "'But' shows contrast between wanting to go out and the rain.",
    hint: "Look for an opposite idea."
  },
  {
    id: "eng-p4-syn-l4-1",
    subject: "English",
    grade: "P4",
    topic: "Synthesis Basics",
    level: 4,
    difficulty: "Medium",
    track: "Core",
    type: "multiple",
    prompt: "Combine: 'Tom was tired.' + 'He went to bed early.'",
    helpText: "Join with a conjunction that shows reason.",
    options: [
      "Tom was tired but he went to bed early.",
      "Tom was tired, so he went to bed early.",
      "Tom was tired, or he went to bed early.",
      "Tom was tired, yet he went to bed early."
    ],
    answer: "Tom was tired, so he went to bed early.",
    explanation: "'So' links tiredness as the reason for going to bed early.",
    hint: "Being tired is a reason to sleep early."
  },
  {
    id: "eng-p4-syn-l6-1",
    subject: "English",
    grade: "P4",
    topic: "Synthesis Basics",
    level: 6,
    difficulty: "Hard",
    track: "Core",
    type: "multiple",
    prompt: "Rewrite using 'although': 'It was raining. We played football.'",
    helpText: "Although shows contrast.",
    options: [
      "Although it was raining, we played football.",
      "Although we played football, it was raining.",
      "It was raining although we played football.",
      "We played football although it was raining."
    ],
    answer: "Although it was raining, we played football.",
    explanation: "The rain contrasts with playing football.",
    hint: "Start with 'Although it was raining...'"
  },
  {
    id: "eng-p4-edit-l4-1",
    subject: "English",
    grade: "P4",
    topic: "Editing",
    level: 4,
    difficulty: "Medium",
    track: "Core",
    type: "multiple",
    prompt: "Find the error: 'She go to school every day.'",
    helpText: "Check the verb for 'she'.",
    options: ["go → goes", "school → schools", "every → all", "day → days"],
    answer: "go → goes",
    explanation: "With 'she', the verb should be 'goes'.",
    hint: "She goes, he goes."
  },
  {
    id: "eng-p4-edit-l5-1",
    subject: "English",
    grade: "P4",
    topic: "Editing",
    level: 5,
    difficulty: "Medium",
    track: "Core",
    type: "input",
    prompt: "Fix the spelling: 'I recieved a beutiful present.' Type the corrected word for 'recieved'.",
    helpText: "Common spelling pattern: i before e except after c.",
    options: [],
    answer: "received",
    acceptedAnswers: ["received"],
    explanation: "The correct spelling is 'received' (i before e except after c).",
    hint: "re + ceive"
  },
  {
    id: "eng-p4-infer-l5-1",
    subject: "English",
    grade: "P4",
    topic: "Inference & Vocabulary",
    level: 5,
    difficulty: "Medium",
    track: "Core",
    type: "multiple",
    prompt: "Maya packed her umbrella and raincoat. What is the weather probably like?",
    helpText: "Use clues from what Maya packed.",
    options: ["Sunny and hot", "Rainy", "Snowy", "Windy only"],
    answer: "Rainy",
    explanation: "Umbrella and raincoat suggest rain.",
    hint: "What do you need those items for?"
  },
  {
    id: "eng-p4-infer-l6-1",
    subject: "English",
    grade: "P4",
    topic: "Inference & Vocabulary",
    level: 6,
    difficulty: "Hard",
    track: "Core",
    type: "multiple",
    prompt: "'The auditorium was packed and every seat was taken.' What does 'packed' mean here?",
    helpText: "Think about a full room.",
    options: ["Empty", "Very full", "Broken", "Quiet"],
    answer: "Very full",
    explanation: "'Packed' means crowded or very full.",
    hint: "Every seat was taken."
  },
  {
    id: "eng-p4-comp-l4-1",
    subject: "English",
    grade: "P4",
    topic: "Comprehension MCQ",
    level: 4,
    difficulty: "Medium",
    track: "Core",
    type: "multiple",
    prompt: "Passage: 'Ben fed his fish before breakfast.' When did Ben feed his fish? (A) after lunch (B) before breakfast (C) at night (D) never",
    helpText: "Find the time phrase in the sentence.",
    options: ["after lunch", "before breakfast", "at night", "never"],
    answer: "before breakfast",
    explanation: "The passage says 'before breakfast'.",
    hint: "Re-read the time words."
  },
  {
    id: "eng-p4-comp-l7-1",
    subject: "English",
    grade: "P4",
    topic: "Comprehension MCQ",
    level: 7,
    difficulty: "Hard",
    track: "Core",
    type: "multiple",
    prompt: "Passage: 'Although the trail was steep, Lily reached the top smiling.' How did Lily feel at the top?",
    helpText: "Look at 'smiling' and 'although'.",
    options: ["Angry", "Proud and happy", "Scared", "Bored"],
    answer: "Proud and happy",
    explanation: "Smiling after a steep climb suggests pride and happiness.",
    hint: "Would you smile if you were scared?"
  },
  {
    id: "eng-p4-scramble-l2-1",
    subject: "English",
    grade: "P4",
    topic: "Subject-Verb Agreement",
    level: 2,
    difficulty: "Easy",
    track: "Game",
    type: "input",
    prompt: "Unscramble into a sentence: 'birds / The / sing / beautifully'",
    helpText: "Start with a capital letter subject.",
    options: [],
    answer: "The birds sing beautifully.",
    acceptedAnswers: ["The birds sing beautifully.", "the birds sing beautifully"],
    explanation: "Subject + verb + adverb makes a complete sentence.",
    hint: "The birds..."
  },
  {
    id: "eng-p4-grammar-ninja-l3-1",
    subject: "English",
    grade: "P4",
    topic: "Editing",
    level: 3,
    difficulty: "Easy",
    track: "Game",
    type: "multiple",
    prompt: "Grammar Ninja: Which sentence is CORRECT?",
    helpText: "Dodge the grammar bombs!",
    options: [
      "He don't like apples.",
      "He doesn't like apples.",
      "He not like apples.",
      "He don't likes apples."
    ],
    answer: "He doesn't like apples.",
    explanation: "With 'he', use 'doesn't' + base verb.",
    hint: "He doesn't..."
  },
  {
    id: "eng-p4-word-quest-l2-1",
    subject: "English",
    grade: "P4",
    topic: "Inference & Vocabulary",
    level: 2,
    difficulty: "Easy",
    track: "Game",
    type: "input",
    prompt: "Word Quest: Spell the opposite of 'happy'.",
    helpText: "Collect the letters: s-a-d",
    options: [],
    answer: "sad",
    acceptedAnswers: ["sad"],
    explanation: "The opposite of happy is sad.",
    hint: "Three letters."
  },
  {
    id: "eng-p4-word-quest-l4-1",
    subject: "English",
    grade: "P4",
    topic: "Prepositions & Conjunctions",
    level: 4,
    difficulty: "Medium",
    track: "Game",
    type: "input",
    prompt: "Word Quest: Complete — The book is ___ the shelf. (on/under/in)",
    helpText: "Books usually sit on top of shelves.",
    options: [],
    answer: "on",
    acceptedAnswers: ["on"],
    explanation: "Books are typically on a shelf.",
    hint: "On top of..."
  }
];
