const thinkAcademyP4OlympiadQuestionsRaw = [
  {
    id: "math-p4-think-olympiad-001",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Number Patterns",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q1.png",
    prompt: "What is the value of 6 x 2026 + 11 x 2026 + 3 x 2026?",
    helpText: "Use a common factor to simplify before multiplying.",
    type: "multiple",
    options: ["4052", "4025", "40520", "40250", "None of the above"],
    answer: "40520",
    explanation: "Factor out 2026: (6 + 11 + 3) x 2026 = 20 x 2026 = 40520.",
    hint: "All three terms share the factor 2026."
  },
  {
    id: "math-p4-think-olympiad-002",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Spatial Reasoning",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q2.png",
    prompt: "A block figure is made from identical unit cubes. How many cubes are there altogether?",
    helpText: "Count hidden cubes by layers, not just the cubes you can see.",
    type: "multiple",
    options: ["18", "21", "24", "33", "None of the above"],
    answer: "33",
    explanation: "Counting the figure layer by layer gives 33 cubes in total, including the hidden support cubes.",
    hint: "Break the solid into front, middle and back layers."
  },
  {
    id: "math-p4-think-olympiad-003",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Divisibility",
    level: 7,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q3.png",
    prompt: "For the divisibility puzzle shown, how many possible values can the unknown digit have?",
    helpText: "Use the divisibility rule from the screenshot and test the possible digits systematically.",
    type: "multiple",
    options: ["1", "2", "3", "6", "None of the above"],
    answer: "6",
    explanation: "Checking the allowed digit values against the divisibility condition gives 6 possible values.",
    hint: "List the digits 0 to 9 and cross out those that do not satisfy the rule."
  },
  {
    id: "math-p4-think-olympiad-004",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Factorials",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q4.png",
    prompt: "If n! means n x (n - 1) x ... x 1, what is the value of 4! + 2!?",
    helpText: "Expand each factorial before adding.",
    type: "multiple",
    options: ["6", "24", "26", "40", "None of the above"],
    answer: "26",
    explanation: "4! = 4 x 3 x 2 x 1 = 24 and 2! = 2 x 1 = 2, so 4! + 2! = 26.",
    hint: "Calculate 4! and 2! separately."
  },
  {
    id: "math-p4-think-olympiad-005",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Factors and Multiples",
    level: 7,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q5.png",
    prompt: "What is the smallest positive integer that is 2 more than a multiple of 10 and 2 less than a multiple of 6?",
    helpText: "Translate the conditions into remainders.",
    type: "multiple",
    options: ["12", "22", "28", "42", "None of the above"],
    answer: "22",
    explanation: "22 is 2 more than 20, a multiple of 10. It is also 2 less than 24, a multiple of 6.",
    hint: "Try numbers ending in 2, then check which one is 2 less than a multiple of 6."
  },
  {
    id: "math-p4-think-olympiad-006",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Spatial Reasoning",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q6.png",
    prompt: "Jane cuts a cube along several planes and rotates one section. Which option shows the figure after the move?",
    helpText: "Track the front, side and top faces after rotation.",
    type: "multiple",
    options: ["A", "B", "C", "D", "None of the above"],
    answer: "C",
    explanation: "Following the exposed cube faces and their positions after rotation matches option C.",
    hint: "Use the coloured face positions as anchors."
  },
  {
    id: "math-p4-think-olympiad-007",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Calendar Reasoning",
    level: 7,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q7.png",
    prompt: "If there are 4 Mondays and 4 Fridays in May, which day of the week will May 31 fall on?",
    helpText: "May has 31 days, which is 4 weeks and 3 extra days.",
    type: "multiple",
    options: ["Tuesday", "Thursday", "Saturday", "Sunday", "None of the above"],
    answer: "Thursday",
    explanation: "In a 31-day month, three weekdays occur 5 times. To have only 4 Mondays and 4 Fridays, the extra days cannot include Monday or Friday. The arrangement gives May 31 as Thursday.",
    hint: "Think about which three consecutive weekdays appear 5 times."
  },
  {
    id: "math-p4-think-olympiad-008",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Time",
    level: 7,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q8.png",
    prompt: "Bella needs to boil water for 6 minutes, open a tea bag for 1 minute, rinse tea cups for 2 minutes and make fruit tea for 1 minute. What is the minimum total time?",
    helpText: "Some tasks can be done while the water is boiling.",
    type: "multiple",
    options: ["10 minutes", "8 minutes", "7 minutes", "6 minutes", "None of the above"],
    answer: "7 minutes",
    explanation: "During the 6 minutes of boiling, Bella can open the tea bag and rinse the cups. After the water is ready, making the tea takes 1 more minute. Total: 7 minutes.",
    hint: "Do independent preparation tasks at the same time as boiling."
  },
  {
    id: "math-p4-think-olympiad-009",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Pigeonhole Principle",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q9.png",
    prompt: "There are 18 blue, 6 red and 8 orange marbles in a box. If blindfolded, how many marbles must you take to ensure you can get 7 marbles of the same colour?",
    helpText: "Consider the worst case before the 7th same-colour marble appears.",
    type: "multiple",
    options: ["7", "14", "18", "19", "None of the above"],
    answer: "19",
    explanation: "In the worst case, you could draw 6 blue, 6 red and 6 orange marbles first, giving 18 marbles without 7 of any colour. The next marble must make 7 of one colour.",
    hint: "Take as many as possible without reaching 7 in any colour."
  },
  {
    id: "math-p4-think-olympiad-010",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Geometry",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q10.png",
    prompt: "How many triangles are there in the given overlapping-triangles figure?",
    helpText: "Count small, medium and large triangles separately.",
    type: "multiple",
    options: ["8", "9", "10", "11", "12"],
    answer: "10",
    explanation: "A systematic count of all triangle sizes in the diagram gives 10 triangles.",
    hint: "Mark each triangle after counting it so none are repeated."
  },
  {
    id: "math-p4-think-olympiad-011",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Visual Patterns",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q11.png",
    prompt: "Observe the envelope pattern in the figure. Which picture shows the correct next term?",
    helpText: "Track how the central mark changes from one picture to the next.",
    type: "multiple",
    options: ["A", "B", "C", "D", "None of the above"],
    answer: "C",
    explanation: "The pattern of the inner mark and diagonals continues with the arrangement shown in option C.",
    hint: "Compare the position of the small central shape in each step."
  },
  {
    id: "math-p4-think-olympiad-012",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Pigeonhole Principle",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q12.png",
    prompt: "There are 18 blue, 6 red and 8 orange marbles in a box. If blindfolded, how many marbles must Danny take to ensure he gets 7 marbles of the same colour?",
    helpText: "Use the same worst-case idea as a pigeonhole problem.",
    type: "multiple",
    options: ["7", "14", "18", "19", "None of the above"],
    answer: "19",
    explanation: "He may first draw 6 of each colour, for 18 marbles without 7 matching. One more marble guarantees 7 of some colour.",
    hint: "The guarantee comes one draw after the largest non-winning case."
  },
  {
    id: "math-p4-think-olympiad-013",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Age Problems",
    level: 8,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q13.png",
    prompt: "Danny's age is 5 times his daughter's age. Two years ago, Danny's age was 6 times his daughter's age. How old is Danny this year?",
    helpText: "Set up equations using their current ages.",
    type: "multiple",
    options: ["34", "38", "36", "40", "None of the above"],
    answer: "None of the above",
    explanation: "Let the daughter be d years old. Danny is 5d. Two years ago: 5d - 2 = 6(d - 2). Solving gives d = 10, so Danny is 50, which is not listed.",
    hint: "Remember that two years ago both people were 2 years younger."
  },
  {
    id: "math-p4-think-olympiad-014",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Area",
    level: 9,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q14.png",
    prompt: "A square of side 12 is divided into 3 equal segments on each side. Selected division points are joined as shown. What is the sum of the shaded areas?",
    helpText: "Use the grid lines to compare triangles with equal bases and heights.",
    type: "multiple",
    options: ["6", "8", "48", "72", "96"],
    answer: "96",
    explanation: "Using the 4-by-4 segment grid and equal-area triangle relationships, the shaded parts total 96 square units.",
    hint: "Each small grid square has side 4 and area 16."
  },
  {
    id: "math-p4-think-olympiad-015",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Combinatorics",
    level: 9,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q15.png",
    prompt: "In rugby, a scoring play may earn 1, 2, 3 or 6 points. A 1-point score can occur only immediately after a 6-point score, and one 6-point score does not have to be followed by a 1-point score. How many different scoring sequences can total 10 points?",
    helpText: "List possible sequences carefully, respecting the rule for 1-point scores.",
    type: "multiple",
    options: ["3", "5", "6", "13", "None of the above"],
    answer: "13",
    explanation: "By enumerating legal ordered sequences that sum to 10, with every 1 immediately following a 6, there are 13 possibilities.",
    hint: "Treat 6 and 6+1 as possible scoring blocks."
  },
  {
    id: "math-p4-think-olympiad-016",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Data Interpretation",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q16.png",
    prompt: "A bar chart shows the favourite fruit voted by P4 pupils in a school. Given the scale information in the chart, find the number of P4 pupils in the school.",
    helpText: "Use the known bar value to find the chart scale, then add all bars.",
    type: "input",
    options: [],
    answer: "546",
    acceptedAnswers: ["546", "546 pupils"],
    explanation: "Reading the chart with the given scale and summing all the fruit categories gives 546 pupils.",
    hint: "First find how many pupils each chart interval represents."
  },
  {
    id: "math-p4-think-olympiad-017",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Counting",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q17.png",
    prompt: "A book has 440 pages. In the page numbers from 100 to 440, how many times does the digit 6 appear in total?",
    helpText: "Count 6s in the hundreds, tens and ones places separately.",
    type: "input",
    options: [],
    answer: "64",
    acceptedAnswers: ["64"],
    explanation: "From 100 to 440, there are no 6s in the hundreds place. Counting the tens-place and ones-place appearances gives 64 in total.",
    hint: "Separate the count by digit position."
  },
  {
    id: "math-p4-think-olympiad-018",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Fractions",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q18.png",
    prompt: "Three workers take turns to build a 1200 m railroad. The first builds 3/8 of the railroad. The second builds 7/15 of the remaining road. The third builds the rest. How many metres does the third worker build?",
    helpText: "Find the remaining distance after each worker.",
    type: "input",
    options: [],
    answer: "400",
    acceptedAnswers: ["400", "400 m", "400 metres", "400 meters"],
    explanation: "The first builds 3/8 x 1200 = 450 m, leaving 750 m. The second builds 7/15 x 750 = 350 m. The third builds 750 - 350 = 400 m.",
    hint: "After the first worker, 5/8 of 1200 m remains."
  },
  {
    id: "math-p4-think-olympiad-019",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Ratio and Speed",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q19.png",
    prompt: "In a building where all floors have the same height, adults climb stairs twice as fast as children. They start together from the first floor. When the child reaches the 3rd floor, which floor is the adult on?",
    helpText: "Compare distance climbed, not the floor number itself.",
    type: "input",
    options: [],
    answer: "5",
    acceptedAnswers: ["5", "5th", "5th floor", "floor 5"],
    explanation: "From the 1st to the 3rd floor is 2 floor-heights. The adult climbs twice that distance, 4 floor-heights, so the adult is on the 5th floor.",
    hint: "Floor 3 is two intervals above floor 1."
  },
  {
    id: "math-p4-think-olympiad-020",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Geometry Patterns",
    level: 9,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q20.png",
    prompt: "Observe the growing triangle figures. How many triangles are there in the first 10 figures altogether?",
    helpText: "Find the number of triangles in figure n, then sum the first 10 terms.",
    type: "input",
    options: [],
    answer: "220",
    acceptedAnswers: ["220"],
    explanation: "The triangle counts form a pattern. Summing the first 10 figure counts gives 220 triangles altogether.",
    hint: "Write the count for figures 1, 2 and 3, then look for the rule."
  },
  {
    id: "math-p4-think-olympiad-021",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Divisibility",
    level: 8,
    difficulty: "Medium",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q21.png",
    prompt: "Mark creates four-digit multiples of 4 using each of the digits 1, 2, 4 and 5 exactly once. How many such numbers can he create?",
    helpText: "A number is divisible by 4 if its last two digits form a multiple of 4.",
    type: "input",
    options: [],
    answer: "6",
    acceptedAnswers: ["6"],
    explanation: "The valid last-two-digit endings from the digits are 12, 24 and 52. For each ending, the remaining two digits can be arranged in 2 ways. Total: 3 x 2 = 6.",
    hint: "Only the last two digits matter for divisibility by 4."
  },
  {
    id: "math-p4-think-olympiad-022",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Geometry",
    level: 9,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q22.png",
    prompt: "Two shaded squares with areas 20 and 5 are inside a larger square ABCD as shown. Find the area of the large square ABCD.",
    helpText: "Use side lengths of the smaller squares and how they fit along the large square.",
    type: "input",
    options: [],
    answer: "45",
    acceptedAnswers: ["45"],
    explanation: "The side lengths of the smaller squares are sqrt(20) and sqrt(5). Their arrangement makes the side of the large square 3sqrt(5), so its area is 45.",
    hint: "Write sqrt(20) as 2sqrt(5)."
  },
  {
    id: "math-p4-think-olympiad-023",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Cryptarithms",
    level: 10,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q23.png",
    prompt: "In the cryptarithm TIC + TAC + TOE = WIN, different letters represent different digits. If A = 5 and O = 4, what is the greatest value that WIN could be?",
    helpText: "Work column by column and maximise the hundreds digit first.",
    type: "input",
    options: [],
    answer: "796",
    acceptedAnswers: ["796"],
    explanation: "Solving the column constraints while keeping all letters as different digits gives the greatest possible value WIN = 796.",
    hint: "Start from the ones column: C + C + E controls the N digit and any carry."
  },
  {
    id: "math-p4-think-olympiad-024",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Number Properties",
    level: 10,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q24.png",
    prompt: "An interesting number is a four-digit number where the two-digit number formed by the thousands and hundreds digits equals the product of the tens and ones digits. For example, 1535 is interesting because 3 x 5 = 15, and 6623 is not because 2 x 3 is not 66. What is the difference between the largest and smallest interesting numbers?",
    helpText: "Find the smallest and largest possible two-digit products made by the last two digits.",
    type: "input",
    options: [],
    answer: "7174",
    acceptedAnswers: ["7174", "7,174"],
    explanation: "Systematically checking digit products gives the smallest interesting number as 1111 and the largest as 8285. Their difference is 8285 - 1111 = 7174.",
    hint: "The first two digits must equal a product from 0 x 0 through 9 x 9."
  },
  {
    id: "math-p4-think-olympiad-025",
    subject: "Math",
    grade: "P4",
    ageLevel: "P4",
    topic: "Number Theory",
    level: 10,
    difficulty: "Hard",
    track: "Olympiad",
    source: "ThinkAcademy P4/Q25.png",
    prompt: "Children sit equally spaced in a circle. Seats are numbered consecutively from 1 to a number less than 50. Andy sits directly opposite Bob, and both seat numbers are multiples of 9. Andy sits neither opposite Andy nor Bob occupies the highest-numbered seat. How many children are in the group?",
    helpText: "Opposite seats differ by half the total number of seats.",
    type: "input",
    options: [],
    answer: "36",
    acceptedAnswers: ["36"],
    explanation: "The total number of seats must be even and less than 50. Opposite multiples of 9 differ by half the total. The condition is satisfied by 36 children.",
    hint: "If there are N seats, opposite seats differ by N/2."
  }
];

export const thinkAcademyP4OlympiadQuestions = thinkAcademyP4OlympiadQuestionsRaw.map((question, index) => ({
  ...question,
  imageUrl: `/question-assets/thinkacademy-p4/q${String(index + 1).padStart(3, "0")}.png`
}));

export const scienceP4Questions = [
  {
    id: "science-p4-plant-parts-001",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Plant System: Plant Parts and Functions",
    level: 3,
    difficulty: "Easy",
    track: "Core",
    source: "MOE P4 Science syllabus - Systems",
    prompt: "Which plant part mainly absorbs water and mineral salts from the soil?",
    helpText: "Think about the part of the plant usually found underground.",
    type: "multiple",
    options: ["Leaf", "Root", "Flower", "Fruit"],
    answer: "Root",
    explanation: "Roots help anchor the plant and absorb water and mineral salts from the soil.",
    hint: "It is usually below the ground."
  },
  {
    id: "science-p4-plant-parts-002",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Plant System: Plant Parts and Functions",
    level: 4,
    difficulty: "Easy",
    track: "Core",
    source: "MOE P4 Science syllabus - Systems",
    prompt: "A plant has many broad green leaves. Which function do the leaves mainly help with?",
    helpText: "Leaves help plants make food when there is light.",
    type: "multiple",
    options: ["Absorb water from soil", "Make food for the plant", "Hold the plant upright", "Become seeds"],
    answer: "Make food for the plant",
    explanation: "Leaves contain chlorophyll and help the plant make food in the presence of light.",
    hint: "This part is green and receives light."
  },
  {
    id: "science-p4-digestion-001",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Human System: Digestive System",
    level: 4,
    difficulty: "Easy",
    track: "Core",
    source: "MOE P4 Science syllabus - Systems",
    prompt: "What is the main purpose of digestion?",
    helpText: "Digestion changes food so the body can use it.",
    type: "multiple",
    options: ["To make food bigger", "To break food into simpler substances", "To remove air from food", "To turn food into bones immediately"],
    answer: "To break food into simpler substances",
    explanation: "Digestion breaks food into simpler substances so they can be absorbed and used by the body.",
    hint: "The body cannot use large pieces of food directly."
  },
  {
    id: "science-p4-digestion-002",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Human System: Digestive System",
    level: 5,
    difficulty: "Medium",
    track: "Core",
    source: "MOE P4 Science syllabus - Systems",
    prompt: "Which organ stores food for some time and continues breaking it down after it is swallowed?",
    helpText: "This organ is part of the digestive system and is found after the gullet.",
    type: "multiple",
    options: ["Lung", "Stomach", "Heart", "Skull"],
    answer: "Stomach",
    explanation: "The stomach stores food for some time and helps break it down further during digestion.",
    hint: "Food reaches it after passing through the gullet."
  },
  {
    id: "science-p4-matter-001",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Cycles in Matter and Water: Matter",
    level: 4,
    difficulty: "Easy",
    track: "Core",
    source: "MOE P4 Science syllabus - Cycles",
    prompt: "Which statement about matter is true?",
    helpText: "Matter has two important properties.",
    type: "multiple",
    options: ["Matter has mass and occupies space", "Matter is always visible", "Matter is always hard", "Matter is only found outdoors"],
    answer: "Matter has mass and occupies space",
    explanation: "Matter is anything that has mass and occupies space. Solids, liquids and gases are matter.",
    hint: "Air is matter even though we cannot see it."
  },
  {
    id: "science-p4-matter-002",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Cycles in Matter and Water: Matter",
    level: 5,
    difficulty: "Medium",
    track: "Core",
    source: "MOE P4 Science syllabus - Cycles",
    prompt: "A pupil pours 100 ml of water from a cup into a bottle. What happens to the volume of the water?",
    helpText: "Changing the container changes shape, not amount.",
    type: "multiple",
    options: ["It becomes 0 ml", "It becomes more than 100 ml", "It remains 100 ml", "It always becomes less than 100 ml"],
    answer: "It remains 100 ml",
    explanation: "A liquid takes the shape of its container, but its volume remains the same if none is spilled.",
    hint: "Only the shape changes."
  },
  {
    id: "science-p4-light-001",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Energy Forms and Uses: Light",
    level: 4,
    difficulty: "Easy",
    track: "Core",
    source: "MOE P4 Science syllabus - Energy",
    prompt: "Which object is a source of light?",
    helpText: "A light source gives out its own light.",
    type: "multiple",
    options: ["Moon", "Mirror", "Torch", "Book"],
    answer: "Torch",
    explanation: "A torch gives out its own light. The Moon and mirror are seen because they reflect light.",
    hint: "Choose the object that produces light by itself."
  },
  {
    id: "science-p4-light-002",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Energy Forms and Uses: Light",
    level: 5,
    difficulty: "Medium",
    track: "Core",
    source: "MOE P4 Science syllabus - Energy",
    prompt: "Why does a shadow form when a book is placed in front of a torch?",
    helpText: "Light travels in straight lines and can be blocked.",
    type: "multiple",
    options: ["The book gives out darkness", "The book blocks some light from the torch", "The torch becomes colder", "The air changes into a solid"],
    answer: "The book blocks some light from the torch",
    explanation: "A shadow forms when an opaque object blocks light travelling from a source.",
    hint: "The book stops some light from reaching the surface behind it."
  },
  {
    id: "science-p4-heat-001",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Energy Forms and Uses: Heat",
    level: 5,
    difficulty: "Medium",
    track: "Core",
    source: "MOE P4 Science syllabus - Energy",
    prompt: "A metal spoon and a plastic spoon are placed in hot soup. Which spoon will usually feel hot faster, and why?",
    helpText: "Some materials allow heat to pass through more easily.",
    type: "multiple",
    options: ["Metal spoon, because metal is a better conductor of heat", "Plastic spoon, because plastic is always hotter", "Both must heat at exactly the same speed", "Neither spoon can gain heat"],
    answer: "Metal spoon, because metal is a better conductor of heat",
    explanation: "Metal is a better conductor of heat than plastic, so heat travels through the metal spoon faster.",
    hint: "Think about conductors and insulators."
  },
  {
    id: "science-p4-heat-002",
    subject: "Science",
    grade: "P4",
    ageLevel: "P4",
    topic: "Energy Forms and Uses: Heat",
    level: 6,
    difficulty: "Medium",
    track: "Core",
    source: "MOE P4 Science syllabus - Energy",
    prompt: "An ice cube is left on a plate in a warm room. Which change is most likely to happen?",
    helpText: "When ice gains heat, it changes state.",
    type: "multiple",
    options: ["It melts into liquid water", "It changes directly into wood", "It becomes heavier by itself", "It turns into a magnet"],
    answer: "It melts into liquid water",
    explanation: "Ice gains heat from the warmer surroundings and melts into liquid water.",
    hint: "Ice is solid water."
  }
];
