import { readFile, writeFile, access } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const rootDir = path.resolve(__dirname, "../..");

const ENV_FILES = [".env.local", ".env"];

export async function loadEnvFiles() {
  for (const file of ENV_FILES) {
    const filePath = path.join(rootDir, file);
    try {
      await access(filePath);
      const content = await readFile(filePath, "utf8");
      for (const line of content.split("\n")) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const eq = trimmed.indexOf("=");
        if (eq === -1) continue;
        const key = trimmed.slice(0, eq).trim();
        let value = trimmed.slice(eq + 1).trim();
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
          value = value.slice(1, -1);
        }
        if (!process.env[key]) process.env[key] = value;
      }
    } catch {
      // optional file
    }
  }
}

export async function writeEnvLocal(updates) {
  const filePath = path.join(rootDir, ".env.local");
  let lines = [];
  try {
    lines = (await readFile(filePath, "utf8")).split("\n");
  } catch {
    lines = ["# Auto-generated by npm run setup"];
  }

  const map = new Map();
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    map.set(trimmed.slice(0, eq).trim(), trimmed.slice(eq + 1).trim());
  }

  for (const [key, value] of Object.entries(updates)) {
    if (value) map.set(key, JSON.stringify(value));
  }

  const preserved = lines.filter((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return true;
    const key = trimmed.split("=")[0]?.trim();
    return !map.has(key);
  });

  const merged = [
    ...preserved.filter(Boolean),
    ...[...map.entries()].map(([key, value]) => `${key}=${value}`)
  ].join("\n");

  await writeFile(filePath, `${merged}\n`, "utf8");
}

export function getProjectRef() {
  return process.env.SUPABASE_PROJECT_REF || "zitukvkmyduzacnhqcxb";
}

export function getProductionUrl() {
  return process.env.EDUSG_PRODUCTION_URL || "https://edusg-ten.vercel.app";
}
